version: '3.8'

services:
  server:
    image: diploma-backend
    build:
      context: .
      dockerfile: ./src/server/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp_files:/usr/temp
    environment:
      NODE_ENV: 'production'
      PORT: 8089
      VOLUME_NAME: 'diploma-temp-files'
      COMPILE_CONTAINER_TIMEOUT: '20s'
      COMPILE_IMAGE_NAME: 'diploma-compile-client'
    ports:
      - '8089:8089'
  compile_and_run:
    image: diploma-compile-client
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
networks:
  default:
    name: 'diploma-network'
volumes:
  temp_files:
    name: diploma-temp-files
