version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      MYSQL_ROOT_PASSWORD: 'directus'
    volumes:
      - backend-db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - directus

  directus:
    image: directus/directus:v8.8-apache
    ports:
      - '8080:80'
    environment:
      DIRECTUS_APP_ENV: 'production'
      DIRECTUS_AUTH_PUBLICKEY: 'some random secret'
      DIRECTUS_AUTH_SECRETKEY: 'another random secret'
      DIRECTUS_DATABASE_HOST: 'mysql'
      DIRECTUS_DATABASE_PORT: '3306'
      DIRECTUS_DATABASE_NAME: 'directus'
      DIRECTUS_DATABASE_USERNAME: 'directus'
      DIRECTUS_DATABASE_PASSWORD: 'directus'
    volumes:
      - ./data/config:/var/directus/config
      - uploads:/var/directus/public/uploads
    networks:
      - directus

volumes:
  backend-db:
  uploads:

networks:
  directus:
#
# docker-compose run --rm --entrypoint "/bin/sh -c" directus "/var/directus/bin/directus install:database"
# docker-compose run --rm --entrypoint "/bin/sh -c" directus "/var/directus/bin/directus install:install -e <email> -p <password> -t C++ -T <acces-token>"
#
